### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by mwmadsen67** [wenchonglai/doggie-slides#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
  - [x] Should look similar to real site
  - [x] When errors are displayed, the form adjusts properly
- [x] Smooth, bug free navigation
  - [x] Login errors clears when switching from login form to sign up form (and vice-versa)
  - [x] Errors should display for both `/signup` and`/login`.
- [x] Adequate and appropriate seeds
  - [x] Demo Login Works

**Comment by mwmadsen67** [comment]
I know you completed this, just putting it here

**Comment by wenchonglai** [comment]
Aside from 'Demo User', I added another link afterwards to test the switch account features and ensure users can be redirected to a different default page once they log out and log into a different account. This temporary link will be removed at the end of this FSP.
